apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::190203316789:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1AS9XRKXWCXMZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::190203316789:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-07T09:19:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1573"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 04628f97-82fb-4b61-9b5b-756a6130a5cf
